---
# Variable setup.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Setup/install tasks.
- name: Setup task for RedHat
  include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: Configure keepalived
  include_tasks: configuration.yml
